### ISSUE TITLE
Roave\BetterReflection\Reflector\Exception\IdentifierNotFound

### ISSUE THREAD

**Issue by fideism** [Roave/BetterReflection#1048]
```
PHP Fatal error:  Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Psr\Http\Server\MiddlewareInterface" could not be found in the located source in path/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:30
Stack trace:
#0 path/vendor/roave/better-reflection/src/Reflector/ClassReflector.php(40): Roave\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier()
#1 path/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(977): Roave\BetterReflection\Reflector\ClassReflector->reflect()
#2 path/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(1289): Roave\BetterReflection\Reflection\ReflectionClass->reflectClassForNamedNode()
#3 [internal function]: Roave\BetterReflection\Reflection\ReflectionClass->Roave\BetterReflection\Reflection\{ in path/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 30

Fatal error: Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Psr\Http\Server\MiddlewareInterface" could not be found in the located source in path/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:30
Stack trace:
#0 path/vendor/roave/better-reflection/src/Reflector/ClassReflector.php(40): Roave\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier()
#1 path/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(977): Roave\BetterReflection\Reflector\ClassReflector->reflect()
#2 path/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(1289): Roave\BetterReflection\Reflection\ReflectionClass->reflectClassForNamedNode()
#3 [internal function]: Roave\BetterReflection\Reflection\ReflectionClass->Roave\BetterReflection\Reflection\{ in path/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 30
```

composer autoload_classmap exists

**Comment by kukulich** [comment]
@fideism Please upgrade BetterReflection first. You don’t use the latest version.

**Comment by Ocramius** [comment]
Besides that, `IdentifierNotFound` is a valid exception to be thrown.

Beeds better/more precise issue with actual reproducible problem.

Closing here.
