### ISSUE TITLE
Need to report which files are unparseable.

### ISSUE THREAD

**Issue by Danack** [Roave/BetterReflection#192]
Scenario - I'm trying to analyze a large library and all the classes in it. One (or more) of the files that are being included in the parsing are not valid PHP files. In this case because I'm accidentally including a test file.

Currently what happens is that a PHPParser exception escapes, and has no useful information about what file contains the problem.

It would be good to catch all PHPParser exceptions inside BetterReflection, and to throw a more specific BetterReflectionException, that contains the information about which file was being parsed or other specific problem, so that it can be fixed, without using the force.

Current output, doesn't say which file caused the problem:
```
PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected T_DEC, expecting '[' on line 14 in /home/github/John/John/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:277
Stack trace:
#0 /home/github/John/John/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(58): PhpParser\ParserAbstract->parse('--FILE--\n<?php\n...')
#1 /home/github/John/John/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(29): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), '--FILE--\n<?php\n...')
#2 /home/github/John/John/vendor/roave/better-reflection/src/SourceLocator/Ast/Locator.php(67): PhpParser\Parser\Multiple->parse('--FILE--\n<?php\n...')
#3 /home/github/John/John/vendor/roave/better-reflection/src/SourceLocator/Ast/Locator.php(49): BetterReflection\SourceLocator\Ast\Locator->findReflectionsOfType(Object(BetterReflection\Reflector\ClassReflector), Object(BetterReflection\SourceLocator\Located\LocatedSource), Object(BetterReflection\Identifier\IdentifierType))
#4 /home/github/John/John/vendor/roa in /home/github/John/John/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 277
```

Repo code:
```
<?php

use BetterReflection\Reflector\ClassReflector;
use BetterReflection\SourceLocator\Type\SingleFileSourceLocator;
use BetterReflection\SourceLocator\Type\AggregateSourceLocator;


ini_set('memory_limit','768M');

$autoloader = require __DIR__.'/../vendor/autoload.php';

exec('wget --no-check-certificate https://github.com/Respect/Validation/archive/master.tar.gz');
exec('tar -xvf master');

$extensions = [
    'php',
    'php5',
    'phtml',
    'inc',
    'module',
    'install'
];

$objects = new \RecursiveIteratorIterator(
    new \RecursiveDirectoryIterator("./Validation-master"),
    \RecursiveIteratorIterator::SELF_FIRST
);

//$regexString = '#^.*\.('.implode('|', $extensions).')$#';

// OOPS this line is incorrect, it tries to parse PHP Test files as PHP source
// code files.
$regexString = '#.*\.('.implode('|', $extensions).')#';
$sourceFileIterator = new \RegexIterator($objects, $regexString);


$sourceLocators = [];
foreach ($sourceFileIterator as $key => $sourceFile) {
    echo "$sourceFile \n";
    $sourceLocators[] = new SingleFileSourceLocator($sourceFile);
}

$sourceLocator = new AggregateSourceLocator($sourceLocators);


$reflector = new ClassReflector($sourceLocator);
$reflClass = $reflector->reflect('Respect\Validation\Exceptions\PunctException');

$properties = $reflClass->getProperties();
$methods = $reflClass->getMethods();

var_dump($properties, $methods);

```

**Comment by asgrim** [comment]
Resolved by #194
